project_id = "cdcdlqbjyptamtleitdp"

[functions.r2-upload]
verify_jwt = false

[functions.r2-download]
verify_jwt = false

[functions.r2-delete]
verify_jwt = false

[functions.r2-presign]
verify_jwt = false
