import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, Headphones, Mic2, Music2, Plus, Radio, Search, TowerControl } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

type Station = { id:string; owner_user_id:string; name:string; tagline:string|null; genre:string|null; network_name:string|null; programming_mode:"live"|"music"|"podcast"|"mixed"; is_live:boolean; live_title:string|null; live_started_at:string|null; };
type Show = { id:string; station_id:string; title:string; show_type:string; scheduled_at:string|null; duration_minutes:number; status:string; };

export default function RadioStationsPage(){
 const {user}=useAuth(); const navigate=useNavigate();
 const [stations,setStations]=useState<Station[]>([]); const [shows,setShows]=useState<Show[]>([]); const [loading,setLoading]=useState(true); const [creatorOpen,setCreatorOpen]=useState(false); const [scheduleStation,setScheduleStation]=useState<Station|null>(null); const [query,setQuery]=useState("");
 const load=async()=>{ setLoading(true); const [{data:s},{data:h}]=await Promise.all([
  (supabase as any).from("radio_stations").select("id,owner_user_id,name,tagline,genre,network_name,programming_mode,is_live,live_title,live_started_at").eq("is_public",true).order("is_live",{ascending:false}).order("created_at",{ascending:false}),
  (supabase as any).from("radio_station_shows").select("id,station_id,title,show_type,scheduled_at,duration_minutes,status").in("status",["scheduled","live"]).order("scheduled_at",{ascending:true}).limit(40)
 ]); setStations((s||[]) as Station[]); setShows((h||[]) as Show[]); setLoading(false); };
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase(); if(!q)return stations; return stations.filter(s=>[s.name,s.tagline,s.genre,s.network_name].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));},[stations,query]);
 const live=filtered.filter(s=>s.is_live); const mine=filtered.filter(s=>s.owner_user_id===user?.id); const upcoming=shows.filter(s=>s.status==="scheduled").slice(0,10);
 return <div className="min-h-screen bg-background pb-28 text-foreground">
  <header className="sticky top-0 z-20 border-b border-border/70 bg-background/95 px-4 pb-3 pt-3 backdrop-blur"><div className="mx-auto flex w-full max-w-5xl items-center gap-3">
   <button type="button" onClick={()=>navigate("/radio")} className="flex h-11 w-11 items-center justify-center rounded-full bg-muted"><ArrowLeft className="h-5 w-5"/></button>
   <div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-primary">YAJ Radio</p><h1 className="truncate text-xl font-black">Live Stations & Networks</h1></div>
   <button type="button" onClick={()=>setCreatorOpen(true)} className="flex h-11 items-center gap-2 rounded-full bg-primary px-4 text-sm font-black text-primary-foreground"><Plus className="h-4 w-4"/>Create</button>
  </div><div className="mx-auto mt-3 flex w-full max-w-5xl items-center gap-2 rounded-xl border border-border bg-card px-3"><Search className="h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stations, networks, genres…" className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none"/></div></header>
  <main className="mx-auto w-full max-w-5xl space-y-8 px-4 pt-5">
   <section><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-red-500">On Air Now</p><h2 className="text-lg font-black">Live radio shows</h2></div><span className="rounded-full bg-red-500/10 px-2.5 py-1 text-[10px] font-black text-red-500">{live.length} LIVE</span></div>
    {loading?<p className="py-8 text-center text-sm text-muted-foreground">Loading stations…</p>:live.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{live.map(s=><StationCard key={s.id} station={s} shows={shows} mine={s.owner_user_id===user?.id} onChanged={load} onSchedule={()=>setScheduleStation(s)}/>)}</div>:<div className="rounded-2xl border border-dashed border-border bg-card p-6 text-center"><Radio className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-2 text-sm font-bold">No station is live right now</p><p className="mt-1 text-xs text-muted-foreground">Create a station and host a morning show, podcast, mix or interview.</p></div>}
   </section>
   <section><div className="mb-3"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-primary">Discover</p><h2 className="text-lg font-black">Stations & networks</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(s=><StationCard key={s.id} station={s} shows={shows} mine={s.owner_user_id===user?.id} onChanged={load} onSchedule={()=>setScheduleStation(s)}/>)}</div></section>
   {upcoming.length?<section><div className="mb-3"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-primary">Coming Up</p><h2 className="text-lg font-black">Scheduled shows</h2></div><div className="space-y-2">{upcoming.map(show=>{const st=stations.find(x=>x.id===show.station_id); return <div key={show.id} className="flex items-center gap-3 rounded-xl border border-border bg-card p-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><CalendarDays className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{show.title}</p><p className="truncate text-[11px] text-muted-foreground">{st?.name||"YAJ Station"} · {show.scheduled_at?new Date(show.scheduled_at).toLocaleString():"Time TBA"}</p></div></div>;})}</div></section>:null}
   {mine.length?<section><div className="mb-3"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-primary">My Radio</p><h2 className="text-lg font-black">My stations</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{mine.map(s=><StationCard key={s.id} station={s} shows={shows} mine onChanged={load} onSchedule={()=>setScheduleStation(s)}/>)}</div></section>:null}
  </main>
  {creatorOpen?<CreateStationSheet onClose={()=>setCreatorOpen(false)} onCreated={()=>{setCreatorOpen(false);void load();}}/>:null}
  {scheduleStation?<ScheduleShowSheet station={scheduleStation} onClose={()=>setScheduleStation(null)} onSaved={()=>{setScheduleStation(null);void load();}}/>:null}
 </div>;
}

function StationCard({station,shows,mine,onChanged,onSchedule}:{station:Station;shows:Show[];mine:boolean;onChanged:()=>void;onSchedule:()=>void}){
 const navigate=useNavigate(); const nextShow=shows.find(x=>x.station_id===station.id&&x.status==="scheduled");
 const goLive=async()=>{const {error}=await (supabase as any).from("radio_stations").update({is_live:true,live_title:station.live_title||station.name+" Live",live_started_at:new Date().toISOString()}).eq("id",station.id); if(error){toast({title:"Could not go live",description:error.message,variant:"destructive"});return;} onChanged(); navigate("/podcast/live");};
 return <div className="overflow-hidden rounded-2xl border border-border bg-card"><div className="relative h-28 bg-gradient-to-br from-violet-600 via-fuchsia-500 to-cyan-500 p-4 text-white"><div className="relative flex h-full flex-col justify-between"><div className="flex justify-between"><span className="rounded-full bg-black/30 px-2 py-1 text-[9px] font-black uppercase">{station.is_live?"● LIVE":station.programming_mode}</span><TowerControl className="h-5 w-5"/></div><div><p className="text-lg font-black">{station.name}</p><p className="truncate text-[10px] text-white/80">{station.network_name||station.tagline||"Independent YAJ station"}</p></div></div></div>
 <div className="space-y-3 p-3"><div className="flex items-center gap-2 text-[10px] text-muted-foreground">{station.programming_mode==="music"?<Music2 className="h-3.5 w-3.5"/>:<Mic2 className="h-3.5 w-3.5"/>}<span>{station.genre||"Variety"} · {station.programming_mode}</span></div>
 {station.is_live?<div className="rounded-xl bg-red-500/10 p-2.5"><p className="text-[9px] font-black uppercase text-red-500">Now playing live</p><p className="mt-0.5 text-xs font-bold">{station.live_title||"Live Show"}</p></div>:nextShow?<div className="rounded-xl bg-muted p-2.5"><p className="text-[9px] font-black uppercase text-muted-foreground">Next show</p><p className="mt-0.5 text-xs font-bold">{nextShow.title}</p></div>:null}
 <div className="flex gap-2"><button type="button" onClick={()=>toast({title:station.is_live?"Tuning in":"Station followed",description:station.is_live?"Live listener audio will open from this station when the host starts the studio.":"You can find this station here anytime."})} className="flex flex-1 items-center justify-center gap-2 rounded-full bg-primary px-3 py-2 text-xs font-black text-primary-foreground"><Headphones className="h-4 w-4"/>{station.is_live?"Tune In":"Follow"}</button>{mine?<><button type="button" onClick={onSchedule} className="rounded-full border border-border px-3 py-2 text-xs font-black">Schedule</button><button type="button" onClick={goLive} className="rounded-full border border-border px-3 py-2 text-xs font-black">Go Live</button></>:null}</div>
 </div></div>;
}

function ScheduleShowSheet({station,onClose,onSaved}:{station:Station;onClose:()=>void;onSaved:()=>void}){
 const {user}=useAuth(); const [saving,setSaving]=useState(false); const [title,setTitle]=useState(""); const [type,setType]=useState("talk"); const [scheduledAt,setScheduledAt]=useState(""); const [duration,setDuration]=useState(60);
 const save=async(e:FormEvent)=>{e.preventDefault();if(!user||!title.trim()||!scheduledAt)return;setSaving(true);const {error}=await (supabase as any).from("radio_station_shows").insert({station_id:station.id,host_user_id:user.id,title:title.trim(),show_type:type,scheduled_at:new Date(scheduledAt).toISOString(),duration_minutes:duration,status:"scheduled"});setSaving(false);if(error){toast({title:"Could not schedule show",description:error.message,variant:"destructive"});return;}toast({title:"Show scheduled",description:title.trim()+" will appear in YAJ Radio upcoming shows."});onSaved();};
 return <div className="fixed inset-0 z-[110] flex items-end bg-black/55 sm:items-center sm:justify-center" onClick={onClose}><form onSubmit={save} onClick={e=>e.stopPropagation()} className="w-full rounded-t-3xl bg-card p-5 sm:max-w-md sm:rounded-3xl"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-primary">{station.name}</p><h2 className="mt-1 text-xl font-black">Schedule a radio show</h2><p className="mt-1 text-xs text-muted-foreground">Morning shows, live podcasts, interviews, music blocks and recurring programming all start here.</p>
 <div className="mt-4 space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Show title" className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"/><select value={type} onChange={e=>setType(e.target.value)} className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"><option value="talk">Talk show</option><option value="podcast">Live podcast</option><option value="interview">Interview</option><option value="music">Music show</option><option value="mix">DJ / Mix</option></select><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} required className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"/><select value={duration} onChange={e=>setDuration(Number(e.target.value))} className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"><option value={30}>30 minutes</option><option value={60}>1 hour</option><option value={90}>90 minutes</option><option value={120}>2 hours</option></select></div>
 <div className="mt-5 flex gap-2"><button type="button" onClick={onClose} className="flex-1 rounded-full border border-border px-4 py-3 text-sm font-black">Cancel</button><button disabled={saving||!title.trim()||!scheduledAt} type="submit" className="flex-1 rounded-full bg-primary px-4 py-3 text-sm font-black text-primary-foreground disabled:opacity-50">{saving?"Scheduling…":"Schedule Show"}</button></div></form></div>;
}

function CreateStationSheet({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){
 const {user}=useAuth(); const [saving,setSaving]=useState(false); const [name,setName]=useState(""); const [networkName,setNetworkName]=useState(""); const [tagline,setTagline]=useState(""); const [genre,setGenre]=useState(""); const [mode,setMode]=useState<Station["programming_mode"]>("mixed");
 const create=async(e:FormEvent)=>{e.preventDefault();if(!user||!name.trim())return;setSaving(true);const {error}=await (supabase as any).from("radio_stations").insert({owner_user_id:user.id,name:name.trim(),network_name:networkName.trim()||null,tagline:tagline.trim()||null,genre:genre.trim()||null,programming_mode:mode,is_public:true});setSaving(false);if(error){toast({title:"Could not create station",description:error.message,variant:"destructive"});return;}toast({title:"Radio station created",description:"Schedule shows, run music programming, or go live."});onCreated();};
 return <div className="fixed inset-0 z-[100] flex items-end bg-black/55 sm:items-center sm:justify-center" onClick={onClose}><form onSubmit={create} onClick={e=>e.stopPropagation()} className="w-full rounded-t-3xl bg-card p-5 sm:max-w-md sm:rounded-3xl"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-primary">Create on YAJ Radio</p><h2 className="mt-1 text-xl font-black">Start a station or network</h2><p className="mt-1 text-xs text-muted-foreground">Live talk shows, podcasts, interviews, DJ/music blocks, or mixed 24/7 programming.</p>
 <div className="mt-4 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} required maxLength={80} placeholder="Station name" className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"/><input value={networkName} onChange={e=>setNetworkName(e.target.value)} placeholder="Network name (optional)" className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"/><input value={tagline} onChange={e=>setTagline(e.target.value)} placeholder="Tagline" className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"/><input value={genre} onChange={e=>setGenre(e.target.value)} placeholder="Genre or format — Hip-Hop, Talk, News…" className="h-12 w-full rounded-xl border border-border bg-background px-3 text-sm"/>
 <div className="grid grid-cols-4 gap-1.5">{(["mixed","live","music","podcast"] as const).map(item=><button key={item} type="button" onClick={()=>setMode(item)} className={"min-h-11 rounded-xl border text-[10px] font-black capitalize "+(mode===item?"border-primary bg-primary text-primary-foreground":"border-border bg-background")}>{item}</button>)}</div></div>
 <div className="mt-5 flex gap-2"><button type="button" onClick={onClose} className="flex-1 rounded-full border border-border px-4 py-3 text-sm font-black">Cancel</button><button disabled={saving||!name.trim()} type="submit" className="flex-1 rounded-full bg-primary px-4 py-3 text-sm font-black text-primary-foreground disabled:opacity-50">{saving?"Creating…":"Create Station"}</button></div></form></div>;
}