// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-featured-content.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { z } from "npm:zod@^3.25.76";
var get_featured_content_default = defineTool({
  name: "get_featured_content",
  title: "Get featured WHEUAT content",
  description: "List recent public content on WHEUAT (podcasts, videos, songs, battles, or feed posts). Use this to see what creators are publishing.",
  inputSchema: {
    kind: z.enum(["podcasts", "videos", "songs", "battles", "posts"]).describe("Which type of content to fetch."),
    limit: z.number().int().min(1).max(25).default(10).describe("How many items to return (max 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured." }], isError: true };
    }
    const sb = createClient(url, key, { auth: { persistSession: false } });
    const table = kind === "posts" ? "feed_posts" : kind;
    const { data, error } = await sb.from(table).select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/ask-jhi.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var ask_jhi_default = defineTool2({
  name: "ask_jhi",
  title: "Ask Jhi (WHEUAT creative companion)",
  description: "Ask Jhi \u2014 WHEUAT's AI creative companion for indie artists and creators \u2014 a question about content ideas, music, channel growth, or the WHEUAT platform.",
  inputSchema: {
    prompt: z2.string().min(1).max(2e3).describe("The question or request for Jhi.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ prompt }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured." }], isError: true };
    }
    const resp = await fetch(`${url}/functions/v1/ask-jhi`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${key}`
      },
      body: JSON.stringify({ messages: [{ role: "user", content: prompt }] })
    });
    if (!resp.ok || !resp.body) {
      const txt = await resp.text().catch(() => "");
      return { content: [{ type: "text", text: `Jhi error (${resp.status}): ${txt}` }], isError: true };
    }
    const reader = resp.body.getReader();
    const decoder = new TextDecoder();
    let buf = "";
    let out = "";
    let done = false;
    while (!done) {
      const { done: d, value } = await reader.read();
      if (d) break;
      buf += decoder.decode(value, { stream: true });
      let nl;
      while ((nl = buf.indexOf("\n")) !== -1) {
        let line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (line.endsWith("\r")) line = line.slice(0, -1);
        if (!line.startsWith("data: ")) continue;
        const s = line.slice(6).trim();
        if (s === "[DONE]") {
          done = true;
          break;
        }
        try {
          const p = JSON.parse(s);
          const c = p.choices?.[0]?.delta?.content;
          if (c) out += c;
        } catch {
        }
      }
    }
    return { content: [{ type: "text", text: out.trim() || "(no response)" }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "wheuat-mcp",
  title: "WHEUAT",
  version: "0.1.0",
  instructions: "Tools for WHEUAT \u2014 a mobile-first platform for independent artists and creators. Use `get_featured_content` to browse recent podcasts, videos, songs, battles, or posts. Use `ask_jhi` to consult WHEUAT's AI creative companion for content ideas, music, and platform guidance.",
  tools: [get_featured_content_default, ask_jhi_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
