GRANT SELECT, INSERT, UPDATE, DELETE ON public.games TO authenticated;
GRANT ALL ON public.games TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.game_players TO authenticated;
GRANT ALL ON public.game_players TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.game_invites TO authenticated;
GRANT ALL ON public.game_invites TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.game_moves TO authenticated;
GRANT ALL ON public.game_moves TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.game_stats TO authenticated;
GRANT SELECT ON public.game_stats TO anon;
GRANT ALL ON public.game_stats TO service_role;