import type { BookPage } from "@/lib/books-catalog";

/**
 * Ember Crown — finished YAJ original adult fantasy novella.
 * 24 substantial reading pages, arranged as eight three-page chapters.
 */
export const EMBER_CROWN_PAGES: BookPage[] = [
  {
    chapter: "Chapter 1 — Cinder Hollow",
    text: `Ryn Ashby had been hammering the same stubborn seam of iron since before dawn when her grandfather called her name from the doorway in a voice too thin for the man who taught her to swing a hammer. Corwin Ashby had run Cinder Hollow forge for forty-one years and never sounded like this. “Leave the seam. Come sit.” He told her his chest had been wrong for months. He hadn’t wanted her working scared. He was running out of mornings for pretend. Ryn felt cold settle beneath her ribs—orphan fear built around one soot-streaked old man and a forge. “You’ll get better,” she said with more force than conviction. “Maybe,” Corwin said. “Either way, there’s something in the chest behind the anvil I should have shown you years ago.” He pointed to the locked iron-banded chest. “It’s time you knew what our family actually guards. Not horseshoes. Something more dangerous.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 1 — Cinder Hollow",
    text: `The chest opened with a key Corwin kept beneath his shirt. Inside, wrapped in oiled cloth, sat a crown of dark simple iron, hammer marks uneven as tools no living smith still used. Even cooled it held faint warmth. “This is the Ember Crown,” Corwin said. “Forged by Maren Ashby for a king who wanted to know when people lied. It burns liars—hot enough that no one mistakes it for coincidence.” The king’s grandson wore it constantly and mistook terror for falsehood until war followed. Afterward Ashby smiths took it back and hid it. “We’ve kept it because power this precise is dangerous in hands most eager to hold it.” Ryn understood. “You’re passing the duty to me.” “To whoever’s left,” Corwin said gently. “Which, very soon, is going to be you.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 1 — Cinder Hollow",
    text: `Corwin declined slowly over following weeks. Ryn ran the shop mostly alone and spent evenings hearing crown history before his memory slipped. He gave her Maren’s journal: never wear it for curiosity, never in anger, never let power become habit. Ryn tested it one night—set it on her head, thought a small lie about finishing a seam, and the crown flared so hot she yanked it off gasping. She sat in the dark forge understanding the stories had not exaggerated. Whatever burden her grandfather passed was undeniably real. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 2 — The Duke's Messenger",
    text: `Duke Alaric’s steward, Roderic Payne, arrived on market morning on a horse finer than the village usually saw, smiling the practiced smile of a man accustomed to deference. He claimed to inspect forges for ceremonial blades needed for an investiture—the Duke’s health failing, succession to be named. Corwin asked why succession needed ceremony beyond ordinary inheritance. Payne’s answer slid like oil: stability, optics, tradition. Ryn disliked him immediately—friendliness performed hollow. When Payne praised their reputation and asked for blade work within a month, Corwin agreed with guarded eyes. After Payne left, Corwin told Ryn, “Men like that don’t ride for horseshoes alone. Watch what he asks next.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 2 — The Duke's Messenger",
    text: `Payne returned twice, always polite, always circling questions about old family stories—crowns, truth-magic, Ashby secrets told as tavern exaggeration. Ryn answered carefully. At night she read the journal’s warning about rulers who sought the crown not for justice but control. Corwin worsened. On a rain-loud evening he made Ryn swear: if Marrow Hold called for more than blades, she would decide with judgment, not flattery. “The crown is hottest,” he whispered, “when someone wants to keep wearing it.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 2 — The Duke's Messenger",
    text: `The ceremonial blades were finished in three weeks of sleepless craft. Payne inspected them with hungry approval and invited Ryn to present them at Marrow Hold—an old tradition, he said, recently revived. Corwin was too weak to travel. “Go,” he told Ryn. “Take the crown hidden. Use it only if a lie is about to become law.” Ryn packed the wrapped iron beneath travel clothes, kissed her grandfather’s forehead, and rode toward a castle that smelled of polish and fear. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 3 — What the Journal Knew",
    text: `Marrow Hold’s stone swallowed sound. Ryn was housed near the kitchens like useful craft, not guest. She met Lady Elowen Ferris in a garden—young ward of the Duke, soon to be named heir. Elowen asked honest questions about forging and seemed grateful for Payne’s “rescue” of her indebted family. Ryn heard gratitude that had been carefully cultivated. The journal’s pages on engineered dependencies echoed in her mind. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 3 — What the Journal Knew",
    text: `Elowen confessed unease: the Duke’s lucid hours were fewer; Payne guided every candidate away until only she remained. Ryn asked whether Elowen wanted the seat. “I want not to be a tool,” Elowen said. They began meeting in stolen minutes. Ryn did not reveal the crown yet; she revealed patterns—how Payne arrived early to every council, how dissenting nobles found sudden debt complications. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 3 — What the Journal Knew",
    text: `On the second night Ryn showed Elowen the crown in candlelight and explained its rule. Elowen went pale, then steady. “If I’m truly chosen freely, the crown won’t burn him for saying so. If I’m a puppet, it will.” Together they planned: Ryn would invoke the smith’s presentation tradition to stand near the dais at investiture, then force Payne’s claim into open air. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 4 — Ceremony",
    text: `The night before, Ryn sat with the crown on her narrow bed, frightened in the way Corwin’s journal described. Elowen knocked, unable to sleep, fearing conspiracy if Ryn was wrong. “Then we embarrass ourselves,” Ryn said. “But I don’t think I’m wrong.” She admitted the crown hurt enough to be unmistakable. Elowen asked if it would surface on Payne publicly. “That’s the entire point of carrying it,” Ryn said. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 4 — Ceremony",
    text: `The great hall filled with nobles beneath old banners. The Duke sat enthroned, diminished, wrapped in furs. Payne guided pacing in steward’s robes. He called Ryn to present blades “forged in honor of Lady Elowen, chosen by the Duke’s own wisdom and will.” Ryn knelt, set the cushion, then lifted the Ember Crown onto her own head before the court. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 4 — Ceremony",
    text: `“By the Duke’s own wisdom and will,” Ryn repeated, looking at Payne. “Is that true?” The crown flared at Payne’s flinch—visible to all. Murmurs erupted. Ryn raised her voice: the Ember Crown revealed falsehood; it had answered Payne’s claim. Payne called madness. Ryn asked the Duke directly whether he chose Elowen freely or through Payne’s narrowing of options. The Duke’s eyes sharpened for the first time in months. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 5 — Court Truth",
    text: `Chaos filled the hall. Ryn remained kneeling with the crown hot on her brow. The Duke pressed Payne for a plain answer. Payne tried careful justifications; the crown flared at each evasion. Finally Payne admitted guiding succession, discouraging rivals, arranging Elowen’s adoption because a grateful heir would need his continued management. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 5 — Court Truth",
    text: `Elowen stepped forward with controlled fury. “You engineered my family’s debts. You created the ruin so I would be grateful for rescue.” Payne’s silence and the crown’s flare confirmed it. The Duke rose with costly effort and stripped Payne of office on the spot. Guards flanked him. Payne’s bitter look at Ryn promised he had not finished scheming in his own mind, even defeated. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 5 — Court Truth",
    text: `Investiture recessed into honest council. Elowen admitted she might lose the claim now that deliberation was real—and preferred honest uncertainty to false certainty. The Duke summoned Ryn privately, astonished by the artifact, and suggested she take it home rather than install permanent truth-magic at court. Ryn felt relief deeper than triumph. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 6 — The Weight of Being Believed",
    text: `The Duke offered payment, title, a permanent truth-keeper post. Ryn sat with the offer a full day. In the garden Elowen—now more securely considered after honest debate—saw her trouble. Ryn quoted Corwin: certainty becomes addiction. Court ran on low-grade deception that would keep the crown on her head daily. She would refuse. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 6 — The Weight of Being Believed",
    text: `The Duke received refusal with grace and asked only that Ashbys remain available as last resort, not habit. Ryn agreed. Elowen walked her to the gates. “Thank you for believing I was worth fighting for.” “You reminded me of someone stubborn enough to keep asking hard questions,” Ryn said. “Don’t lose that.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 6 — The Weight of Being Believed",
    text: `The journey home was slower, weighted with aftermath. Ryn understood the loneliness of wielding power few could share. She arrived dust-covered to find Corwin waiting by the cooling forge, thinner, fiercely awake with fear spent on her absence. “You’re home.” “I’m home,” she said, setting down the satchel with the crown wrapped inside. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 7 — Return to the Forge",
    text: `Ryn told Corwin everything in unhurried installments. He was proud she refused court. He admitted nearly staying at a lord’s court in youth until his father talked him out of it: the crown is most dangerous when you want to keep wearing it. Setting it down returns you to ordinary trust. Ryn said she had felt that temptation after Payne’s confession—and chosen the cloth and the road home instead. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 7 — Return to the Forge",
    text: `Corwin’s health plateaued unexpectedly. Ryn returned the crown to its chest and found satisfaction in ordinary commissions. Elowen’s letter arrived months later: succession confirmed honestly; Payne exiled. I understand why your family hides it, Elowen wrote, and why I hope we never need it again. Ryn kept the letter by forge-light, settled. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 7 — Return to the Forge",
    text: `Autumn harvest brought repair work and evenings of equal conversation between keepers. Ryn asked if the crown protected against Payne’s kind of fear—the need to abolish uncertainty. Corwin said it couldn’t cure that fear, only force daylight when fear curdled into structural harm. Ryn understood why forty years held only a handful of uses: not finding lies for sport, but knowing when a lie stopped being survivable. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 8 — Set Down",
    text: `A spring message from two valleys away requested Ashby certainty for an inheritance dispute. Corwin handed Ryn the letter: judgment now belonged to the one who would wear it. Ryn read the texture of the conflict and decided ordinary magistrates should try first. Save the crown for structural deception, not convenience. Corwin smiled. “Then you’ve answered the only question that mattered.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 8 — Set Down",
    text: `Years of ordinary iron followed. Elowen visited once without banners, asking about tempering steel for craft apprentices. They drank tea and laughed about Payne’s careful smile, edges worn soft. Elowen asked if Ryn regretted refusing court. Ryn touched the locked chest. “Power that never rests becomes another kind of lie. I prefer work that cools overnight.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 8 — Set Down",
    text: `Corwin died the following winter in the forge chair, longer-lived than early predictions. Ryn buried him on the hill and kept the crown wrapped, using it only twice more in a decade, always reluctantly. Most days she worked iron and found steadier warmth in forge fire than crown heat. She wrote her journal entry beneath his: the crown’s value lived in the discipline of setting it down. Then she closed the book for whoever came after, and opened the forge doors to morning. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
];
