 "@/lib/books-catalog";

/**
 * Orbit Garden — YAJ Originals adult sci-fi novella.
 * 24 substantial reading pages, matching the finished YAJ adult-book format.
 */
export const ORBIT_GARDEN_PAGES: BookPage[] = [
  {
    chapter: "Chapter 1 — The Last Greenhouse",
    text: `Hydroponic vines climbed the curved glass as Station Helix turned toward the sun. Dr. Amara Sol patched a drip line with one gloved hand and steadied a tray of tomato seedlings with the other. Beyond the greenhouse dome, Earth filled half the sky: blue, white, bruised brown, beautiful enough to make homesickness feel like a physical illness. Helix carried the last complete agricultural seed archive known to survive the climate collapse below, and Amara treated every drawer in the vault as if it held a living ancestor. Most of the station crew called the greenhouse Orbit Garden. Amara preferred not to. Gardens were meant to belong to a place. This one was a lifeboat. Still, every morning she spoke softly to the plants while checking nutrient lines, as though they could hear the promise hidden inside routine: not forever. One day, these roots would touch soil again.

She moved down the center aisle with the tablet tucked against her ribs, pausing at each tray long enough to check leaf color and root tension. Every plant aboard Helix had a number, a lineage, a storage twin, and an emergency replacement protocol. That was how frightened civilizations loved things: by documenting them against loss. Amara understood the reason, but the greenhouse still felt most honest before the station fully woke, when the irrigation pumps hummed and nobody was asking her to justify why a tray of peppers deserved electricity. She rested two fingers against the warm casing of the seed vault door. Her mother had died believing Earth would recover someday. Amara had inherited the belief but not the certainty. Lately she had begun to wonder whether Helix was preserving a future—or postponing the moment when someone would have to risk building one.`
  },
  {
    chapter: "Chapter 1 — The Signal",
    text: `The alert came during artificial dawn. Unauthorized object approaching Vault Hatch Three. Amara sealed the greenhouse, clipped herself into the transit rail, and pushed through the central spine toward the airlock. Malik Reyes, systems engineer and the closest thing she had to family aboard Helix, was already there with a diagnostic tablet. “No transponder,” he said. “No registry code either.” Through the outer camera they watched a small drone tumble against the stars, one wing burned black, its casing scarred by atmospheric reentry. It should not have been able to reach orbit. It should not have been able to find them. Director Vale ordered it destroyed from Command. Amara refused before she had time to make the refusal sound diplomatic. “It came from Earth.” Malik looked at her, then at the drone. Together they overrode the disposal sequence and pulled the machine into quarantine.

Malik enlarged the drone’s approach path on his screen. It had climbed from the planet on a crude chemical booster, shed most of its shielding, and coasted the final distance almost blind. “Whoever built this wanted it to arrive more than they wanted it to survive,” he said. Amara stared at the scorched shell through the quarantine glass. A strip of faded green paint ran along one side, hand-applied rather than manufactured. The color affected her more than the damage. Green had become a ceremonial color aboard Helix, printed on archive seals and school emblems. On Earth, someone had wasted paint on a machine. Someone still had enough imagination to decorate a desperate message. When Vale repeated the order to destroy it, Amara keyed the hatch open herself. “Then put my name on the violation,” she said. “It already is.”`
  },
  {
    chapter: "Chapter 2 — Earthside",
    text: `Inside the drone they found no weapon, no pathogen, no living passenger. Only a cracked memory chip wrapped in insulation and a handwritten strip of polymer sealed beneath the casing. AMARA SOL — HELIX BOTANY. The sight of her own name made the room go quiet. The chip was damaged, but Malik recovered fragments: satellite maps, soil readings, water tables, and field notes tagged with coordinates from the old western agricultural zone. The readings made no sense. Organic nitrogen was rising. Fungal networks had returned in pockets once declared sterile. Moisture retention was increasing where the dust storms had thinned. Someone on Earth had been testing soil. Someone knew enough about Helix to address the message to her. The final intact file contained one sentence: WE CAN GROW AGAIN. Amara read it three times before realizing her hands were shaking.

The coordinates were precise enough to be frightening. Amara overlaid them on pre-collapse survey maps and found old irrigation channels, groundwater basins, and abandoned agricultural research stations. Whoever had assembled the files understood agronomy, not just survival. There were repeated measurements over months, not a single lucky reading. Carbon content rose in the same plots where fungal density returned. Trace metals were dropping after seasonal runoff. A recovery pattern. Malik leaned closer to the display. “If this is fabricated, it’s the most patient lie I’ve ever seen.” Amara barely heard him. She was looking at one image buried among the data: a hand holding a clump of dark soil. Tiny white roots threaded through it. No face, no caption, just proof that something below had been willing to grow. For twenty-three years, Helix had described Earth in past tense. The photograph made that grammar feel suddenly obscene.`
  },
  {
    chapter: "Chapter 2 — The First Tray",
    text: `That night Amara withdrew six tomato seeds, four beans, two wheat kernels, and a pinch of basil from the archive. She recorded every movement twice. The experiment was technically unauthorized because the retrieved soil sample data had not been validated, but she no longer cared about the distinction between caution and fear. Malik synthesized the mineral profile from the drone readings while Amara adjusted the greenhouse tray to match Earthside conditions. They lowered the nutrient support, introduced the harsher mineral balance, and switched the lighting to mimic a dusty terrestrial dawn. The tray looked ordinary when she finished. A rectangle of dark growing medium beneath a strip of pale light. Yet standing over it, Amara felt as if she had opened a door. In the official log she wrote only: Experimental terrestrial profile initiated. In her private notes she wrote what she actually believed: Orbit is temporary. Roots are the mission.

She stayed beside the tray long after Malik left. The simulated soil smelled wrong compared with the sterilized growth medium used elsewhere on the station—mineral, dusty, faintly metallic. She imagined real wind moving over real ground, carrying spores and grit and all the uncontrolled variables Helix engineers had spent decades eliminating. The thought frightened her and made her want it more. Before sealing the experiment bay, she added one more sensor to the tray and lowered the camera angle so the first sign of germination would be impossible to miss. In the station corridor, a group of schoolchildren passed on their way to lessons. One girl pointed through the glass and asked her teacher what Amara was growing. “A test,” the teacher answered. Amara stopped walking. The answer was technically correct. Still, under her breath, she said, “A way back.”`
  },
  {
    chapter: "Chapter 3 — Council",
    text: `Director Elias Vale called an emergency council session the next morning. The drone, he said, represented an unacceptable breach. Earth had been classified as agriculturally unstable for twenty-three years. Helix existed because the seed archive could not be risked on hope. Amara presented the recovered data. Vale presented models showing catastrophic uncertainty. “We are custodians,” he told her. “Not pioneers.” Amara had heard the phrase before. It had been written into Helix doctrine after the final evacuation waves: preserve, catalogue, wait. But waiting had become its own culture. Children had been born aboard the station who had never felt rain. Entire departments existed to protect a future no one was willing to attempt. Amara pointed to the fungal readings. “This isn’t hope. It’s evidence.” Vale’s answer was calm. “Evidence from a broken drone sent by an unknown source.” The council voted to quarantine the chip and suspend her experiment. Five to two.

After the vote, no one met Amara’s eyes in the corridor. Council decisions were supposed to produce clarity; this one only exposed the size of the fear holding Helix together. Malik caught up with her at the transit ring and handed back the copy of her presentation he had been annotating. Across the top he had written, in large letters, FIVE PEOPLE VOTED AGAINST A TOMATO. She almost laughed. Almost. “They voted against risk,” she said. Malik shrugged. “Same thing, if you let fear write the dictionary.” Back in the greenhouse she stood outside the sealed experiment bay, forbidden to touch the tray until further notice. The dark growing medium looked inert. She knew better than to expect movement so soon. Yet she kept checking the camera feed anyway, every hour, as if attention itself might coax life through the surface.`
  },
  {
    chapter: "Chapter 3 — Germination",
    text: `The tomato seed sprouted anyway. Amara found the first green hook pushing through the dark medium thirty-seven hours later. She called Malik without speaking; she only turned the camera toward the tray. He stared, then laughed once, sharp with disbelief. The soil profile was incomplete and the conditions were harsh, yet the seedling had done what life had always done when given the smallest chance: it reached. Amara recorded measurements until her eyes blurred. The bean followed. Then basil. Vale ordered the trial terminated when he learned of the growth. Amara stood between the tray and the security team. “You can destroy it,” she said, “but then you’re not protecting the archive. You’re protecting the station from being wrong.” No one moved. Malik quietly broadcast the live greenhouse feed onto the public station channel. Within minutes half of Helix was watching a five-centimeter tomato shoot bend toward artificial light.

The broadcast spread faster than Command could contain it. By midday, residents had begun gathering outside the greenhouse windows. Mechanics arrived still wearing tool belts. Children pressed their palms to the glass. An elderly woman from Habitat Three asked whether the seedling was truly growing under Earth-matched conditions, and when Amara said yes, she started crying without embarrassment. Vale appeared at the edge of the crowd and watched in silence. Amara could see the conflict in him: the administrator who wanted control and the survivor who understood exactly what a green shoot meant. The tomato had no idea it had become political. It kept unfolding one small leaf. Amara found that comforting. Life was indifferent to policy. It did not wait for unanimous approval. It tested conditions, used what was available, and moved toward light.`
  },
  {
    chapter: "Chapter 4 — A Voice in the Static",
    text: `The drone had one more secret. Buried under corrupted telemetry, Malik recovered a repeating burst transmission. It was too weak for Command to notice, but once isolated it resolved into a voice. A woman. Breathless, older, speaking over wind. “Helix, if you receive this, Valley Nine is alive. We have water. We have soil. We need seeds, not rescue. Repeat: seeds, not rescue.” The recording ended in static. Amara knew Valley Nine from childhood maps. It had once been a research basin in the high desert, later an emergency settlement, then a blank zone after communication collapsed. The message was eight months old. Vale argued that eight months made it useless. Amara argued that someone had survived long enough to build a drone, find Helix’s orbit, and send it upward. “They did their part,” she said. “Now we decide whether preservation means keeping seeds in drawers or returning them to the world.”

Malik cleaned the audio until the woman’s voice became almost intimate, as if she were standing in the room with them. Beneath the wind, Amara could hear metal rattling and, farther away, something like children shouting. She made him replay that section. “There,” she said. “Again.” The voices were indistinct, but they were real. Valley Nine was not merely a laboratory transmitting automated data. People were there. Families, perhaps. A community stubborn enough to repair transmitters while rationing food. Amara copied the message to three private drives before Command could seal it. That night she listened through headphones in her bunk, hearing the phrase seeds, not rescue over and over. The wording mattered. Valley Nine was not asking Helix to become a savior. They were asking for partnership. For tools. For trust. The distinction made Amara more certain that she had to answer.`
  },
  {
    chapter: "Chapter 4 — The Archive",
    text: `Helix’s seed vault occupied three decks behind armored doors. Amara walked its aisles that evening alone. Rice from flood-resistant lines. Maize bred for heat. Millet. Lentils. Cassava tissue samples. Orchard stock held in cryogenic suspension. Every label carried a place name like a gravestone. Kenya. Punjab. Iowa. Ceará. Luzon. Sicily. Her mother had helped load some of these crates before Amara was old enough to understand what evacuation meant. “Seeds are memory with instructions,” she used to say. Amara placed her hand against a cold storage cabinet and finally understood why the phrase had always frightened her. Memory that never returned to use became a museum. Helix had become expert at remembering Earth. Perhaps the harder duty was trusting it again.

At the end of the third aisle she found a drawer labeled SOL COLLECTION — EAST AFRICA / COASTAL ADAPTIVES. Her mother’s surname had been attached to the archive because she had coordinated one of the last emergency seed transfers before launch. Amara had known the fact all her life, but standing there now, she felt its weight differently. Her mother had not packed those seeds so they could remain perfect forever. She had packed them because someday imperfect people would need them. Amara pulled up the transfer manifest on her wrist display and saw her mother’s digital signature beside a note: FOR RESTORATION WHEN CONDITIONS ALLOW. Not preservation. Restoration. She closed her eyes. The argument had been hidden inside the archive the whole time. Helix had remembered only the first half of its purpose because the second half required courage.`
  },
  {
    chapter: "Chapter 5 — The Hidden File",
    text: `Malik found evidence that someone aboard Helix already knew about the Valley Nine transmission. A command archive showed the station had received two weak Earthside signals six months earlier, both classified and buried under emergency protocol. Vale’s authorization code was attached. Amara confronted him privately. He did not deny it. “The first signal was incomplete,” he said. “The second could not be authenticated.” “So you chose silence?” “I chose not to gamble the last viable seed archive on a desperate message.” His voice cracked only once. Vale had been a child during the food riots. He had watched a regional seed bank burn after officials opened it too early and armed groups seized the stock. “I know what hope can cost,” he said. Amara softened, but not enough to retreat. “And I know what fear costs when it becomes policy.”

Vale sat behind his desk without the usual wall display active. Without maps and risk models glowing around him, he looked less like a director and more like the exhausted man Amara remembered from childhood evacuation drills. He told her about the seed bank he had seen raided when he was nine. Families had trampled one another outside a facility that opened its stores after a drought. Armed crews took most of the grain before organized distribution could begin. “My mother called it hope without infrastructure,” he said. Amara listened. She did not excuse the buried signals, but she understood the wound beneath the decision. “Then help me build the infrastructure,” she said. “Don’t use an old failure as proof that nobody gets to try again.” Vale looked at her for a long time. He did not agree. But for the first time, he did not dismiss her either.`
  },
  {
    chapter: "Chapter 5 — A Plan",
    text: `The station had one surface-capable shuttle remaining: Cedar, designed for archive recovery missions that had never been approved. Its heat shield was aging but intact. Its cargo bay could carry a limited seed bank, water recyclers, soil scanners, and three people. Amara proposed a reconnaissance mission, not a full transfer. Take duplicate stock only. Confirm Valley Nine. Return with live soil, water, and human testimony. Malik volunteered before she finished. Dr. Hana Cho from medicine joined next, arguing that any surviving settlement needed more than botany. The council split. Vale threatened to lock down Cedar. Then the public channel filled with messages from residents who had watched the tomato sprout. For the first time in years, Helix was not debating survival in the abstract. People were asking what survival was for.

They spent the next two days turning hope into checklists. Malik reviewed Cedar’s life-support loops and discovered three valves that would need replacement before reentry. Hana built a medical inventory around the assumption that Earthside clinics had little sterile equipment. Amara selected duplicate seed stock with ruthless restraint, choosing resilience over sentiment: millet before strawberries, beans before roses, drought-tolerant maize before the heirloom melons she secretly loved. Every choice reminded her that restoration was not a symbolic act. It was logistics, biology, and limits. Outside the planning room, residents volunteered skills faster than the council could process them. A teacher offered curriculum support for Valley Nine. Two mechanics asked to restore a second shuttle. Even people who opposed the mission began discussing what would happen if it succeeded. Amara realized institutions often changed only after ordinary people started behaving as if change had already begun.`
  },
  {
    chapter: "Chapter 6 — Departure",
    text: `Cedar left Helix during station night. Officially, the mission was “provisional planetary verification.” Unofficially, half the station gathered at the observation windows to watch. Amara strapped into the shuttle beside Malik while Hana ran through medical checks for the third time. The seed case between them contained less than one ten-thousandth of Helix’s archive, yet it felt heavier than the ship. As the station receded, Earth grew until it filled the forward glass. Amara had spent her entire adult life looking down at the planet. Descending toward it felt like falling into a memory she did not personally own. Clouds rushed closer. Lightning flickered inside a storm front over the southern ocean. Malik whispered, “Still beautiful.” Amara answered, “Still ours.”

As docking clamps released, Amara felt a vibration travel through Cedar’s frame and into her bones. Helix rotated beyond the window, familiar and impossibly small. The greenhouse dome flashed once in sunlight. She pictured the tomato vine inside, tied carefully to its support, and wondered whether anyone had remembered to lower the nutrient flow that morning. Malik caught her expression. “You’re worried about the plants while we’re falling toward a planet.” “They’re my plants.” “Of course.” Hana smiled from the seat behind them. “Good. Worry about something normal.” Then Earth filled the glass, and normal disappeared. Amara placed one gloved hand on the seed case between her boots. Generations had carried these lines through war, drought, migration, freezing, storage, and orbit. Now she was asking them to survive one more transition: from being protected symbols back into living crops.`
  },
  {
    chapter: "Chapter 6 — Reentry",
    text: `The atmosphere hit Cedar like a fist. Heat alarms screamed. The shuttle bucked hard enough to blur the instrument panel. Hana swore in three languages while Malik fought a guidance fault. Amara watched the external temperature climb and thought absurdly of the basil seedlings back on Helix. Then the turbulence broke. The clouds opened beneath them. Earth. Not the dead gray sphere from old disaster reports, but a vast patchwork of color. Scarred land, yes. Dry riverbeds. Abandoned cities. Yet also green threading along waterways, algae shining in reclaimed wetlands, and scrub forests spreading where suburbs had once stood. The planet had not healed. But it had not stopped trying. Cedar descended toward Valley Nine on manual control.

Cloud tops rushed past like mountains of white fire. When the worst of reentry ended, Amara realized she had been holding her breath. Below them, river systems shone through brown plains. Some coastlines had changed. Several cities were visible only as pale grids beneath vegetation and silt. Yet there were unmistakable signs of recovery everywhere once she knew how to look: green corridors tracing water, marshes widening into former industrial zones, dark bands of forest where suburbs had burned decades earlier. Earth was wounded, not empty. The difference hit her with such force that she gripped the harness. Malik pointed to the navigation display. “Valley Nine beacon acquired.” A tiny light blinked. Someone below had powered it for them. Someone expected them to come. Cedar banked toward the signal, and for the first time in Amara’s life, the horizon was not curved by a station window.`
  },
  {
    chapter: "Chapter 7 — Valley Nine",
    text: `They landed beside a cracked solar field half buried in sand. No one greeted them at first. Wind moved through the remains of a fence. Then figures emerged from low structures cut into the hillside. Twenty people. Then forty. Then more. At the front stood an older woman with silver hair under a scarf and a weather-beaten tablet in her hand. “Dr. Sol?” she asked. Amara could only nod. The woman introduced herself as Mara Venn, agronomist, former Earth Recovery Network. She had sent the drone. Behind her, children stared at Cedar as if it were a myth that had landed. One boy held up a carrot no longer than Amara’s thumb. “We grew this,” he said proudly. Amara knelt to see it better. She had to blink hard before answering. “Then you already started without us.”

The people of Valley Nine did not cheer when Cedar landed. They watched cautiously until the engines cooled, as if experience had taught them that miracles usually came with paperwork or danger attached. Mara Venn stepped forward first. She and Amara studied each other with the strange familiarity of two people who had been arguing toward one another from different worlds. “You got my drone,” Mara said. “Barely.” “It was built from irrigation parts and an old weather booster.” Malik let out a low whistle. “That explains several engineering crimes.” The tension broke. People laughed. Then the boy with the tiny carrot approached, and Amara felt the history of Helix collapse into that ridiculous orange root. Valley Nine had not waited for permission to become the future. They had improvised it badly, bravely, one crop at a time. She realized her job was not to arrive as an expert. It was to listen before planting anything.`
  },
  {
    chapter: "Chapter 7 — The Soil",
    text: `Valley Nine’s fields were small and uneven, protected by wind barriers made from old transit panels. The survivors had rebuilt irrigation from a buried municipal line and cultivated soil using compost, algae cultures, and fungal inoculants. The first years had failed repeatedly. Crops yellowed. Roots burned. Dust swallowed beds overnight. But the ecosystem had begun to change. Lichens returned to rock. Insects appeared near seasonal water. Native grasses anchored the slopes. Mara showed Amara a test plot where hardy legumes had survived three seasons. “The planet is doing more work than we are,” she said. “We just learned to stop fighting the process.” Amara pressed both hands into the soil. It was gritty, cool beneath the surface, and alive with the smell of minerals and decay. Real soil. Nothing aboard Helix had ever smelled like this.

Amara spent the afternoon on her knees in the field, crumbling samples between her fingers and comparing them with the drone data. The soil was inconsistent from bed to bed, but inconsistency itself was a sign of life. Sterile substrates were uniform. Living ground was messy—roots, insects, decayed leaves, fungal threads, stones, pockets of moisture. Mara showed her where the first worms had appeared after a wet season. People had celebrated for two days. “You celebrated worms?” Malik asked. “You spend twenty years without them and see how glamorous they get,” Mara replied. Amara laughed, then went quiet when she saw a patch of clover growing beyond the managed plots with no irrigation at all. It had returned on its own. She crouched beside it. The leaves were small and wind-scarred. They were also free. Helix had spent decades safeguarding life. Earth had spent those same decades quietly manufacturing chances.`
  },
  {
    chapter: "Chapter 8 — The Price of Return",
    text: `Hope did not erase difficulty. Valley Nine had food shortages, failing batteries, respiratory illness, and only one reliable water pump. Their population could survive, but not expand safely without support. Hana spent two days treating infections while Malik repaired the solar array. Amara ran germination tests with seeds from Cedar. Wheat struggled. Beans held. Millet thrived. A drought-tolerant tomato variety opened its first leaves under Earth sunlight. Every success created a new question: how much could Helix send without endangering the archive? How quickly could a surface network distribute seeds without repeating the chaos Vale feared? Amara began designing a distributed system instead of a single drop — small seed libraries, locally managed, genetically diverse, each able to replenish the others. Preservation would no longer live in one station or one valley. It would live in many hands.

Mara helped Amara map the settlement’s weaknesses without disguising them. The north pump had failed twice in one season. Battery storage dropped dangerously low after dust storms. Several residents had chronic lung damage from early years above ground. The valley’s apparent green was fragile, supported by constant maintenance. This was exactly the kind of complexity Vale had feared—and exactly why simple yes-or-no arguments about returning had been inadequate. Amara adjusted her plan that evening. The goal would not be to move the archive to Earth. The goal would be to create living redundancy between orbit and multiple surface communities. No single place would again be asked to carry the future alone. She sketched circles on a paper map: Helix at the top, Valley Nine below, empty circles for settlements not yet contacted. Malik looked over her shoulder. “A network.” “A garden,” Amara said. This time she meant the word differently.`
  },
  {
    chapter: "Chapter 8 — Vale’s Decision",
    text: `Amara transmitted their findings to Helix. Soil scans, water reports, medical data, live footage of Valley Nine, and a video of the first tomato seedling opening beneath natural sun. Vale watched from orbit in silence. The council reconvened. This time Amara did not argue from emotion. She laid out redundancy models, seed replacement rates, transport capacity, and risk limits. Malik demonstrated that the archive could support controlled releases for decades without compromising core diversity. Mara spoke directly to the council from Earth. “We are not asking you to save us,” she said. “We are asking you to stop saving seeds from us.” The vote passed nine to one. Vale cast the only dissenting vote. Then, after the tally, he authorized the release protocol himself.

Vale requested a private channel after the council session ended. His face filled the small display in Valley Nine’s operations room. For several seconds neither of them spoke. Finally he said, “You understand that one successful valley does not prove planetary stability.” “Yes.” “And that twelve cases of seed are not a civilization.” “Yes.” His mouth tightened. “You have become annoyingly difficult to argue with.” Amara smiled. He looked away, then back. “I authorized the protocol because your redundancy plan addresses the failure I witnessed as a child. Not because I have suddenly become optimistic.” “I’ll take responsible pessimism.” “You always did.” Before ending the call, Vale asked to see the tomato under natural sunlight. Amara turned the camera toward the test bed. The leaves moved slightly in the breeze. Vale stared longer than necessary. When the screen went dark, Amara understood that his vote had been no, but his decision afterward had been something more complicated—and more useful.`
  },
  {
    chapter: "Chapter 9 — First Planting",
    text: `The first official Helix seed delivery arrived six weeks later. Not thousands of crates. Twelve sealed cases. Carefully selected. Enough to begin, not enough to dominate. Amara stood with Valley Nine residents as they opened the cases beneath a shade canopy. Each packet was logged twice and assigned to a local steward. Children learned how to record germination rates. Elders mapped old wells. Farmers who had survived on improvised crops began testing varieties their grandparents had once known. The work was slow, procedural, sometimes frustrating. It was also the most alive Amara had ever felt. She realized she had spent years thinking her job was to protect possibility. Now possibility had become responsibility.

Each case opened with a hiss of pressure equalization. Inside, packets sat in foam channels beside printed cultivation notes and digital backups. There was no ceremony planned, but people gathered anyway. Mara insisted the first packets go not to the most experienced growers but to mixed teams: one elder, one younger resident, and one person trained in record keeping. “Knowledge has to survive the same way seed does,” she said. Amara approved immediately. The children treated germination logs like sacred documents for almost six hours before someone drew a cartoon sun in the margin. Amara left it there. By afternoon the valley was full of small arguments about spacing, shade, and water allocation. She had never heard anything more hopeful. Real restoration sounded less like music than like neighbors disagreeing over compost while carrying trays together. That evening she transmitted the first planting report to Helix with one line at the top: Archive release successful. Future currently muddy.`
  },
  {
    chapter: "Chapter 9 — Rain",
    text: `The rain came in the middle of planting. Not a storm, just a thin sheet moving across the valley, enough to darken the dust and send everyone running outside. Amara stood in it without a hood. Water touched her face, cold and uneven. She had studied rainfall cycles, modeled precipitation, watched storms from orbit — but she had never felt rain fall from a real sky. Malik laughed at her expression. “Botanist finally meets water,” he said. She shoved him lightly and kept looking upward. Around them, children opened their mouths to the clouds. Mara placed seed trays beneath the shelter and smiled. The rain lasted eleven minutes. By evening, the valley smelled different. Richer. Amara understood then why people had written songs about weather.

Amara walked beyond the shelters after the rain, boots sinking slightly into softened ground. Droplets clung to every leaf. The valley had changed color in minutes, dust turning from pale tan to deep rust and brown. She picked up a handful of wet soil and held it under her nose. The scent was enormous—fungus, stone, plant matter, water, history. Her mother had tried to describe petrichor once when Amara was a child aboard Helix. She had called it “the smell of the planet remembering itself.” At the time Amara thought the phrase sentimental. Now she understood the precision of it. Malik came to stand beside her without speaking. Farther down the slope, children were stomping in puddles until Mara shouted at them to stay out of the test beds. Amara laughed so hard she cried. The rain had been brief, but nothing about it felt small.`
  },
  {
    chapter: "Chapter 10 — Return to Helix",
    text: `Amara returned to Helix after three months on the surface. She expected the station to feel like home. Instead it felt like a place she loved and had outgrown at the same time. The greenhouse was brighter than she remembered. The original tomato trial now climbed nearly two meters along the curved glass, heavy with fruit. Residents had tied small notes to the support frame: FOR EARTH. FOR MY GRANDMOTHER. FOR RAIN. Vale met Amara beside the tray. He looked older. “You were right,” he said. She shook her head. “Not entirely.” He glanced at her. “That is a suspiciously diplomatic answer.” “You were right about risk. I was right about movement. We needed both.” For the first time, he smiled without authority in it.

Before leaving Valley Nine, Amara collected three sealed soil cores, microbial samples, pollen traps, and handwritten notes from every crop steward who would give her one. She also carried a small paper bag Mara slipped into her hand at the landing pad. Inside was the crooked little carrot the boy had shown her on arrival, now dried and saved for seed. “Not scientifically impressive,” Mara warned. “Historically impressive,” Amara replied. Back on Helix, she placed the bag beside the original drone casing in the archive exhibit space. Vale objected that neither item met conservation standards. Amara told him history rarely did. Residents came by all week to look. The carrot became more popular than several million preserved accessions, which annoyed the archivists and delighted Malik. For Amara, it was proof that preservation meant more when people could point to what came next.`
  },
  {
    chapter: "Chapter 10 — The New Mission",
    text: `Helix changed slowly because institutions always did. The station remained the central archive, but its mission statement was rewritten. PRESERVE became PRESERVE, CULTIVATE, RESTORE. Training programs opened for surface ecology. Children learned soil science alongside orbital navigation. Cedar began regular runs to Earth, and two additional shuttles were restored from storage. Signals arrived from other settlements once Valley Nine’s broadcast spread: coastal enclaves, mountain reservoirs, an underground community near the old Great Lakes. Not every message could be answered quickly. Not every place was ready. But Earth was no longer silent.

The new mission statement appeared first on official documents, then on corridor screens, then on the wall outside the seed vault in letters large enough to make avoidance impossible: PRESERVE. CULTIVATE. RESTORE. Some residents resisted the change. Helix had been built around the moral certainty that staying apart was safest. Surface missions complicated that certainty. Amara did not dismiss their fear. She organized open briefings and published failure reports alongside successes. Two early test shipments spoiled because of bad seals. One shuttle launch was delayed for months. A Valley Nine wheat trial failed almost completely. None of those setbacks ended the project. That became its own lesson. Restoration did not require perfect confidence; it required systems capable of surviving mistakes. Children began competing for places in ecology training. Teachers requested real soil samples for classrooms. For the first time, Earth was not taught only as the world that had been lost.`
  },
  {
    chapter: "Chapter 11 — The Network",
    text: `Within two years, nine regional seed libraries operated on the surface. None held everything. That was the point. Each community protected part of the genetic archive while exchanging stock through scheduled routes. If one failed, the others remained. Farmers sent data back to Helix: which wheat tolerated new heat patterns, which beans resisted revived pests, which fruit trees could survive shifting seasons. The archive stopped being a frozen collection and became a conversation between past and present. Amara divided her time between orbit and Earth, though everyone knew where she preferred to sleep. Gravity gave her sore muscles and peace.

The nine libraries were deliberately different. Coastal communities received salt-tolerant lines. High-elevation settlements focused on cold-hardy grains. Valley Nine became the center for drought adaptation and soil recovery. Helix retained deep backups and genetic reference stock while surface growers generated new data every season. The information flowed both directions. One farmer discovered a bean variety performed better when planted beside a revived native shrub; the finding forced Helix scientists to revise an old nutrient model. Amara loved moments like that. Expertise was becoming distributed too. Earthside growers were no longer recipients of orbital knowledge. They were producing it. Malik joked that the archive had finally learned to listen. Amara corrected him: “We finally learned the archive was never the smartest thing in the room.” The smartest thing was the network—people, seeds, microbes, weather, memory, and error all teaching one another how to continue.`
  },
  {
    chapter: "Chapter 11 — Roots",
    text: `At Valley Nine, the first orchard began with twelve young trees. Apricot, fig, pomegranate, olive. Children who had once known fruit mostly from preserved rations helped dig the planting holes. Amara watched a girl named Tessa pat soil around a sapling and ask how long before it gave food. “A few years,” Amara said. Tessa frowned. “That’s forever.” Mara laughed. “That’s gardening.” The answer stayed with Amara. Helix had been built by people terrified there would be no future. The orchard required people willing to invest in a future they might not personally harvest. Perhaps that was the difference between surviving and belonging.

Tessa returned every week to check the orchard, though the trees changed too slowly to satisfy her. She measured one apricot sapling with a piece of marked string and accused it of being lazy. Amara showed her how new buds formed and how roots expanded invisibly before branches could. “So most of the work is underground?” Tessa asked. “A lot of important work is.” The girl considered that, then tied the string loosely around the trunk for next month. Watching her, Amara thought about Helix. For years, the station had looked motionless from the outside, but perhaps some of that long preservation had been underground work too—preparation waiting for the right conditions. She no longer needed to condemn the past in order to move beyond it. Preservation had kept the possibility alive. Restoration gave the possibility somewhere to go.`
  },
  {
    chapter: "Chapter 12 — Orbit Garden",
    text: `Years later, visitors still called the Helix greenhouse Orbit Garden. Amara stopped correcting them. The name had changed meaning. It was no longer a garden stranded above Earth. It was one node in a living system that stretched between orbit and soil. On the greenhouse glass, someone had painted a small symbol: a root curling around a planet. Beneath it were the words Amara had once written privately in a log no one was meant to read. ORBIT IS TEMPORARY. ROOTS ARE THE MISSION. She never discovered who found the entry and turned it into a motto. She decided not to ask.

Visitors from Earth began arriving at Helix for training, and station-born children traveled down for short surface residencies once medical teams approved the program. The greenhouse became the place where the two cultures met easiest. Earthside growers laughed at Helix residents for sterilizing tools too often; Helix botanists were horrified by the amount of dirt everyone tracked into the lab. Amara loved the friction. The greenhouse no longer felt like a lifeboat cut off from shore. It felt like a bridge. On one wall, beneath the painted root-and-planet symbol, residents added the names of every active surface seed library. Valley Nine. Coast Four. Lake Haven. Cerro Verde. North Basin. More names followed. Each one made the station feel less central and more connected. That was exactly what Amara wanted. A future with only one center was too easy to break.`
  },
  {
    chapter: "Chapter 12 — Home",
    text: `Amara’s final transfer to Earth happened on a clear morning. Cedar touched down at Valley Nine beside fields that now reached beyond the original wind barriers. The air smelled of damp soil, basil, diesel, and flowering beans. Malik met her at the landing pad carrying two mugs of terrible coffee. “Welcome home,” he said. Amara looked across the valley. Children moved between garden beds. Solar towers turned toward the sun. Beyond them, green climbed the hills in patient bands. Earth was not restored. It might take generations. There would be droughts, losses, mistakes, and places that never recovered. But the work had begun in the only way real restoration ever began: not with certainty, but with care repeated long enough to become a future. Amara knelt beside a row of tomatoes, pressed her fingers into warm soil, and smiled when the roots held.

Malik handed her the terrible coffee and pointed toward the first orchard, now tall enough to cast narrow shadows. “You’re really staying this time?” he asked. Amara nodded. Helix would always need botanists, but it no longer needed her specifically to guard the future. That was success, not abandonment. She had spent most of her life believing responsibility meant remaining indispensable. Earth had taught her otherwise. Healthy systems distributed care. Healthy gardens did too. She walked past the tomato beds and saw the descendants of the first trial line mixed among local varieties, no longer special enough to receive labels. That pleased her more than any plaque could have. The seed that once proved Earth might be ready had become ordinary food. Someone would eat it for lunch without knowing its history. Amara pressed her hands deeper into the warm ground. The roots resisted gently, alive and tangled. For the first time, home did not feel like a place she was protecting. It felt like a place protecting itself with everyone’s help.`
  },
];
