import type { BookPage } from "@/lib/books-catalog";

/**
 * Recipe for Us — finished YAJ original adult romance novella.
 * 24 substantial reading pages, arranged as eight three-page chapters.
 */
export const RECIPE_FOR_US_PAGES: BookPage[] = [
  {
    chapter: "Chapter 1 — Rival Smoke",
    text: `By noon the festival lot smelled like ambition and chili oil. Food trucks lined the river park in a glittering argument of awnings. Mira Chen wiped her prep board twice, not because it was dirty, but because ritual kept her hands from shaking. Across the aisle, Theo Bard lit the burners on Harbor Stack and pretended not to watch her. They had circled each other for two seasons—same markets, same commissary, same judges smiling carefully. Mira’s Lantern Spoon sold sharp bright plates; Theo built tall sandwiches that made strangers sigh. The city loved them both and loved their rivalry more.

“Try not to set the block on fire,” Theo called.

“Try not to smother your food in spectacle,” Mira answered, and her lengthening line softened the comeback. A volunteer clipped a schedule to her window: finals in ninety minutes. Mira looked at Theo’s truck, then at the sky. Weather granted no continuance. Between garlic and nerve she understood the day’s recipe: cook well, look unafraid, and refuse to let a man with perfect wrists become the story instead of the work. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 1 — Rival Smoke",
    text: `Theo’s first ticket was a kid who wanted no onions and also all the onions philosophically. He handled it with patience earned from burned lunch rushes. Between orders he caught Mira laughing with a regular—head tipped back, towel over one shoulder like a cape she refused to admit she wore. He had liked her before competing with her, which complicated branding. Rivalry sold tickets. Rivalry also made him rehearse conversations in the walk-in.

“You’re staring again,” his runner said.

“Studying technique.”

“Studying her laugh.”

Theo plated a bao with scallion oil so glossy it looked smug. When a judge wandered through, Theo offered heritage-grain sentences; Mira offered chili crisp eggs and said, “Taste it. Then tell me what you need it to mean.” Theo felt pride and panic together. If he lost, he wanted to lose to her. If he won, he wanted her to still look at him like a person, not a scoreboard. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 1 — Rival Smoke",
    text: `By midafternoon the lot became smoke and compliments. Mira’s auntie texted voice notes translating to: stand up straight, feed people, don’t marry a sandwich man unless he washes dishes. Mira sent a heart and a mise photo. Theo appeared at her window during a lull with tasting spoons. “Swap? No commentary. Just information.” His bite was rich and careful; hers was bright enough to wake the dead. “You’re going to take People’s Choice,” Theo said. “You’re going to take the panel,” Mira answered. “Then we’ll both be annoying in different directions.” She almost smiled. “Why are you being decent?” “Because I can cook angry or honest, and only one tastes like me. Also because I hate pretending I don’t care what you think.” Her next customer arrived. The unfinished sentence stayed between them like sauce reducing—thicker every minute. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 2 — Judging Table",
    text: `The finals tent was fluorescent seriousness. Mira plated black vinegar caramel on crisp tofu with herbs like confetti. Theo presented a smoked mushroom melt with chili honey and a pickle that snapped like a punchline. “What inspires you?” a judge asked Mira. “My auntie’s refusal to cook bland food for polite company.” Theo said, “Making something tall enough to look like confidence and tender enough to confess it isn’t,” then winced at his poetry. Mira’s mouth twitched. Outside, photographers wanted rivalry faces. They gave half-smiles and returned to their trucks. Waiting was worse than cooking. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 2 — Judging Table",
    text: `Results came at golden hour. The panel awarded Theo first for technique. People’s Choice went to Mira by a margin that made the emcee joke about democracy tasting like chili crisp. Theo found Mira behind her truck, forehead on cool metal. “Congrats.” “You too. I wanted both. That’s ugly to admit.” “It’s human.” He handed her ginger beer. “I voted for you.” “You did not.” “Anonymously, like a coward with principles.” Mira laughed, surprised into softness. They tapped bottles while string lights came on and the rivalry costume loosened into a simpler hunger: to ask what he ate when nobody scored him. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 2 — Judging Table",
    text: `They closed early and walked the river with leftovers, eating like thieves of their own brands. Mira told him about her first night market at seventeen. Theo told her about crying in a walk-in after a bride sent back pasta for being “too emotional.” “Do you ever get tired of performing appetite?” she asked. “Constantly. Do you get tired of being the sharp one?” “Constantly. Sharp is safer than hoping someone will meet you in the middle.” Theo stopped. “I can meet you in the middle. Tomorrow. Your place after breakdown. No plating for cameras.” “Yes,” Mira said so fast it made her smile. “Bring dessert if you don’t mock sincerity.” “I make no promises,” she said, and meant she would try. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 3 — After Service",
    text: `Breakdown day was grease traps and honesty. Theo arrived at Mira’s apartment with a tote and first-date nerves disguised as prep. Her place was small, bright, full of mismatched bowls and judgmental window herbs. Theo cooked ginger-scallion fish, cucumber salad, sesame rice. Mira made a tomato salad so simple it felt like a dare. They ate with socks touching by accident then choice. “This doesn’t taste like rivalry,” Mira said. “Good. Rivalry is marketing. This is supper.” After dishes they talked until city noise thinned. Theo admitted a pop-up residency he feared she’d read as fleeing. Mira admitted a notes-app menu titled Temporary Truce. “Send it,” he said. “Cook it with me,” she answered. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 3 — After Service",
    text: `Their first collaboration was a Tuesday lunch: her chili crisp on his egg sandwich, his pickles beside her bowls, a sign reading RIVALS SHARE BETTER. The line wrapped the building. Working shoulder to shoulder revealed frictions—Mira hated wasted motion; Theo hummed; she plated like punctuation; he plated like jazz. They snapped twice and repaired before service ended because hunger doesn’t wait for ego. At close, sticky and triumphant, Mira bumped her forehead to his chest. “We’re good at this.” “We’re dangerous at this.” “Then we decide the sequel, not the algorithm.” That night he walked her to the bus and waited while it took her into the lit grid, feeling the peace of wanting without needing to win her like a trophy. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 3 — After Service",
    text: `The kiss happened in the walk-in cooler—unromantic in theory, perfect in practice. Mira reached for cream. Theo said her name like a question. Cold air smoked around them. She rose on her toes and closed the distance before fear could plate a prettier version. It was brief, tasting like sesame and relief. “Too cold?” he asked. “Exactly cold enough to keep me honest.” They returned to the line as if nothing and everything had happened. That evening Mira texted her auntie: He washes dishes. He can stay in the draft. Auntie replied with fire emojis and warnings. Mira sent back: Watching carefully. Cooking carefully too. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 4 — Shared Menu",
    text: `By late summer they ran monthly Soft Landing nights—no judging table, no rivalry hashtags unless customers brought them. Mira handled brightness; Theo handled comfort; together plates felt like conversation. A vendor who monetized their feud accused them of killing the golden goose. Theo shrugged. “Geese should be allowed to date.” Mira said tenderness would not become content first. Sundays they shopped as customers, buying too many peaches, arguing about salt. Mira cleared a pantry shelf. Theo learned upstairs neighbors’ names. The city, busy with appetite, mostly let them become ordinary. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 4 — Shared Menu",
    text: `Ordinary broke when a chain offered Theo a signature residency that glittered and constrained. He spread paperwork on Mira’s table like a fish to clean. “It would pay the truck loan. It would also mean six months of smiling without you.” Mira read the exclusivity clause. “They want your face more than your craft.” “Do you want it?” Theo sat back. “I want security. I want you. I want to stop confusing those as opposites. If I say no, it must be because we’re building something real.” Mira took his hand. “Then we build. A business plan with room for sleep.” They drafted Spoon & Stack until two in the morning. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 4 — Shared Menu",
    text: `Saying no to the chain felt like jumping and finding ground closer than fear claimed. The lease came through in October. They painted the awning badly, then hired Mira’s cousin to fix lettering. Opening weekend rain threatened and politely held off. They sold out by two. A child asked if they were married. Mira said, “Not yet.” Theo dropped a spatula. The child nodded like a tiny contract lawyer and requested extra pickles. That night they ate cold noodles on milk crates behind the truck and called it victory cuisine. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 5 — Heat Check",
    text: `Running one window taught romance versus logistics. Mira owned inventory; Theo owned maintenance; both took turns being wrong out loud. Their first real fight lasted from prep through service and ended in the parking lot with Mira saying “sharp” and Theo saying “scared.” “I’m sharp because you changed the special without telling me.” “I’m scared because I thought surprising you would feel like care and instead felt like erasure.” They fixed the process: shared board, shared veto, shared credit. Then they ate cold noodles and called it reconciliation cuisine. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 5 — Heat Check",
    text: `Winter festivals returned with sharper wind. Spoon & Stack became habit for nearby workers. Mira’s auntie visited, tasted everything, hugged Theo hard, and whispered, “He looks at you like you’re the recipe, not the prize.” That night Theo cooked scallion eggs and toast. “This is what I make when I miss home.” “Then make it whenever. Home can be a pan.” They fell asleep with a cookbook open on the floor, page bent as proof of return. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 5 — Heat Check",
    text: `A magazine asked to profile “the rivalry that became a love story.” They compromised: one interview, no staged fights, quote approval. The piece ran with hands plating side by side. Mira read three comments and stopped. “We don’t live in the comments.” “We live in the ticket window,” Theo said, “and the apartment with the sticky knife drawer.” They celebrated by closing early, splitting pie in a diner booth, writing next season’s menu on napkin paper—greasy and optimistic. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 6 — Service for Two",
    text: `On the anniversary of the festival that changed everything, they returned as guests. Walking the lot without a window felt like time travel. Mira bought a tamale and moaned with respect. Theo bought too many pickles. At the river rail they leaned shoulder to shoulder. “If we hadn’t competed, would we have found this?” Theo asked. “Maybe later. Maybe never. Rivalry got us in the same frame. Choice kept us there.” He kissed her temple with flourless tenderness. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 6 — Service for Two",
    text: `They got a dog named Ladle as a dare Mira could not unsay. Ladle learned truck keys and the moral importance of dropped fries. After a brutal rush Mira sat on the floor with Ladle’s head in her lap. “I used to think rest was what happened when you lost ambition. Now I think rest is how ambition stays edible.” Theo leaned on her shoulder. “Write that on the specials board.” “Never. Private menu.” The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 6 — Service for Two",
    text: `A late-night commissary fire two buildings over forced evacuation. Mira, Theo, and other cooks shared coffee in a parking lot at 2 a.m. watching firefighters move like calm metronomes. No one hurt; priorities rearranged: people first, pans second, press never. Home, unable to sleep, they cooked rice porridge at three. Mira fed Theo a spoonful. “Too much ginger?” “Perfect amount for surviving a feeling.” They ate in bed like rule breakers and slept near dawn. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 7 — Full Plate",
    text: `By their second shared autumn they hired help without panic. Jun plated with monastic focus. Pat handled customers like beloved patients. With oxygen in the schedule, Mira took night finance class; Theo started a Sunday repair clinic for other truck cooks. On a free Wednesday they cooked on a coastal camp stove for no audience. Wind seasoned everything. Mira said, “This is my favorite review.” Theo asked which critic. She gestured at the ocean. “That one. Doesn’t clap. Just stays.” The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 7 — Full Plate",
    text: `Theo proposed after service in the cleaned truck, ring box beside chili crisp. “Cook through the years with me. Rivalry optional. Dish duty mandatory.” Mira cried and laughed and said yes into his neck. Jun and Pat cheered outside. Ladle barked as if she had brokered the deal. Auntie screamed joy through the phone and threatened knives and opinions. Theo called out, “Yes, ma’am.” The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 7 — Full Plate",
    text: `They married in the river park off-season, string lights borrowed, vows short, food abundant. Guests ate standing. Someone toasted rivalry; Mira redirected to repair. Theo’s speech mentioned ginger beer, the walk-in kiss, napkin menus. When they danced Mira whispered, “Still want to compete sometimes?” “Always—at card games, perfect eggs, who loves more obviously.” “I’ll win that last one.” “You already do,” he said, spinning her under a flickering light. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 8 — Soft Landing",
    text: `Years later the awning needed repainting twice and Spoon & Stack still opened weekends by the river. A young cook asked Mira how to turn competition into partnership without losing fire. “Keep the fire,” she said. “Lose the need to burn someone else for warmth. Feed people. Tell the truth early. Wash the pans.” Theo added, “And if you fall in love with your rival, don’t perform it for the comments first.” The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 8 — Soft Landing",
    text: `On a quiet Monday they took Ladle to the empty festival lot. Mira stood where her truck had been; Theo where his had been; then they met in the middle. “Hungry?” he asked. “For what you make when nobody’s scoring,” she said. Home, they cooked eggs with scallion oil and tomato salad. No garnish for cameras. “Perfect,” Mira said. “Even the rivalry?” “Especially what we made from it.” The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
  {
    chapter: "Chapter 8 — Soft Landing",
    text: `Before bed Mira wrote tomorrow’s prep list. Theo finally fixed the sticky drawer. In the kitchen doorway Mira said, “Recipe for us.” “Ingredients?” “Heat, repair, rest, citrus, one stubborn dog, and a city that keeps eating.” “Method?” “Return to the pan. Return to each other. Taste as you go.” He turned off the light. Their hands found each other with practiced ease. Tomorrow: tickets and smoke. Tonight: a rivalry rewritten into a kitchen, and a love that had learned to share a window without disappearing. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave. The afternoon light shifted across ordinary surfaces and made them look briefly ceremonial. She held the moment the way cooks hold a simmer—patient, attentive, unwilling to rush the transformation. Around her the world continued its unglamorous work of hunger and repair, and somehow that steadiness felt like proof that choosing carefully could still be brave.`,
  },
];
