import type { BookPage } from "@/lib/books-catalog";

/**
 * River of Names — finished YAJ original adult fantasy novella.
 * 24 substantial reading pages, arranged as eight three-page chapters.
 */
export const RIVER_OF_NAMES_PAGES: BookPage[] = [
  {
    chapter: "Chapter 1 — The Taking",
    text: `The river above Vel’s village did not flood with water so much as with forgetting. When the mist rose three nights running, names began to thin—first a child’s nickname, then a grandmother’s surname, then the word for the hill path everyone had walked since birth. Sera Kall stood at the bank with salt on her tongue and a ledger of what the current had stolen. Her little brother no longer answered to Tomas; he answered to a blank look when the sound was spoken. Elders said the River of Names woke when the village broke an old bargain: they had dammed a side channel for mills and starved the spirit’s preferred song. Sera did not care about theology. She cared that Tomas laughed without knowing why the laugh belonged to him. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 1 — The Taking",
    text: `Sera’s mother, once a keeper of naming rites, had vanished into mist the previous spring—body never found, name still spoken by stubborn mouths as if insistence could be a rope. Sera inherited her beads and her stubbornness. The village council wanted prayers and patience. Sera wanted a crossing. Old Ferrin the ferryman told her the river would take a living name as toll if she entered seeking what was lost. “Then it can have a piece of mine,” Sera said, tying her hair with her mother’s cord. “Not the whole. A syllable. I can spare a syllable.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 1 — The Taking",
    text: `At dawn she stepped into water cold enough to clarify fear. Mist closed like pages. Beneath the surface she heard syllables tumbling like stones—stolen names knocking against each other. A pale shape drifted near: not a body, a braid of sound. Sera reached, and the river asked without words what she offered. She spoke her middle name aloud—Liora—and felt it peel from her like warm cloth. Painful. Survivable. The mist parted onto a sandbar where names glowed faintly in wet script. Tomas’s name pulsed near the edge. She cupped it carefully, as if heat could spill. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 2 — The Bargain Shore",
    text: `On the sandbar stood a figure woven from reed and reflection, voice like overlapping whispers: the River’s Warden. “You pay in pieces and expect wholes,” it said. “Your people stopped the singing water. Names went hungry.” Sera held Tomas’s name and did not kneel. “Then teach me the song. I’ll open the channel. Give the children back.” The Warden tilted. “One returned name per restored current. And one truth spoken that your village refuses.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 2 — The Bargain Shore",
    text: `Sera returned dripping to a village arguing about mills and pride. She placed Tomas’s name against his forehead in the old rite; recognition flooded his face like color returning to cloth. The council gasped, then feared her method. Ferrin backed her: reopen the side channel. Mill owners shouted ruin. Sera told the truth the Warden required: the dam had been built not only for grain but to claim water rights from downstream kin the council preferred to forget. Silence cracked. Shame, at least, was a kind of remembering. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 2 — The Bargain Shore",
    text: `They broke part of the dam that night by lantern. Water found its old throat and sang thinly. Mist thinned. Two more names washed ashore for Sera to carry home—a midwife’s and a shepherd’s. Each return cost her another small word from her own naming: a childhood nickname, a private joke-name her mother used. She walked home lighter of self and heavier of purpose, learning that rescue was a ledger with her blood as ink. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 3 — Downstream Kin",
    text: `Downstream, the kin-village of Orrel had suffered reverse theft: too many names jammed into dreams, people answering to three identities at once. Sera traveled with Ferrin to trade help for dredging tools. Orrel’s speaker, Maen, recognized Sera’s thinning name-aura immediately. “You’re paying yourself away,” Maen warned. “The river loves willing erasures.” Sera asked how to restore without vanishing. Maen spoke of the First Name Stone upstream—where original bargains were cut—and of a chorus that could share cost among many voices. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 3 — Downstream Kin",
    text: `Together the villages practiced the chorus on the bank: each person offering a single freely given syllable of praise, not identity. The river accepted community sound more gently than solitary sacrifice. Names began returning in pairs. Sera felt her lost middle name flicker at the edge of hearing like a bird outside a window. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 3 — Downstream Kin",
    text: `Mill hardliners sabotaged the open channel at midnight, rolling stones back into the throat. Mist surged. Tomas forgot Sera’s face for one terrifying hour. Sera stood in water to her chest and screamed the sabotage as truth. The Warden appeared and marked the saboteurs’ names with black silt until they confessed. The channel opened again. Tomas remembered and clung to her soaked sleeves as if memory were a rope bridge. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 4 — The First Name Stone",
    text: `Sera, Maen, and Ferrin hiked to the First Name Stone—slate rising from the river’s birth-spring, carved with vows in a language half music. Rain filled the carvings. The vow was clear enough: water sings; people answer with names given freely and kept with care; dams of pride break the exchange. Sera pressed her palm to the stone and offered not another piece of her name but a promise to teach children the rite yearly. The stone warmed. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 4 — The First Name Stone",
    text: `The Warden rose from the spring. “Promises are cheaper than syllables,” it tested. Sera answered by calling the chorus—dozens of voices from both villages who had followed. Shared song rolled over water. Mist loosened into ordinary fog. Names poured back like bright fish. Sera heard Liora return into her chest with a click of rightness that made her weep. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 4 — The First Name Stone",
    text: `Not every name returned clean. Some came tangled—old grudges attached, secrets the river had kept as sediment. The villages had to sit in circle and sort truth from theft, apology from accusation. Sera moderated with blacksmith patience learned from watching disputes over tools: heat, cool, reshape. The work was slower than magic and more durable. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 5 — Mother in the Mist",
    text: `Among returning names was Sera’s mother’s—not as a spoken word alone but as a path of luminous footprints leading into deep mist. Sera followed despite Ferrin’s warning. She found her mother seated on a mid-river rock, half-substantial, tending a braid of orphaned names like a shepherd. “I stayed to keep them from dissolving,” her mother said. “The dam broke more than water. It broke custody.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 5 — Mother in the Mist",
    text: `Sera begged her to walk home. Her mother smiled with river-light eyes. “I can return if someone keeps the braid. Or I remain and you live fully named.” Sera understood the cruel elegance. She refused the binary. “We braid together until the chorus can hold it. Then you come back for soup.” Her mother laughed—a sound Sera had missed like bread. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 5 — Mother in the Mist",
    text: `For seven nights the village rotated watch over the braid of residual names while Sera and her mother taught the rite. On the eighth dawn her mother stepped onto bank mud and left wet footprints that did not fade. Tomas tackled her. The council cried. Sera finally slept without counting absences. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 6 — Flood of Memory",
    text: `With names restored, memories overcrowded—festivals recalled mid-argument, debts remembered with interest. Tempers flared. Sera proposed a Memory Market: not selling memories, but narrating them in stalls so the surplus could be witnessed and set down. The idea felt absurd until it worked. People left lighter. The river’s mist stayed kind. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 6 — Flood of Memory",
    text: `Payback arrived as politics. A regional reeve tried to claim the reopened channel for taxation, renaming it on maps as if paper could own song. Sera carried the Ember-like certainty of lived rite to the reeve’s tent and spoke the First Name Stone vow aloud until the reeve’s own clerks admitted the map was a theft of language. The channel kept its old name. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 6 — Flood of Memory",
    text: `Sera began training apprentices—children who liked lists and courage. One apprentice asked if she was afraid of forgetting herself again. “Yes,” Sera said. “So I practice being known on purpose: I say my names each morning to the water, and the water says them back if I have kept faith.” Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 7 — High Water",
    text: `Spring melt tested the bargain with real flood. The villages chose not to re-dam; they moved grain, lifted floors, sang through the rise. Mist never turned thieving. When waters receded, silt left bright name-seeds in the mud—newborn words for places previously unnamed. Sera catalogued them with delight. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 7 — High Water",
    text: `Ferrin asked Sera to ride his ferry as name-keeper for travelers, a floating rite-station. She agreed part-time, refusing to become only a symbol. Mornings at home, afternoons on water, evenings teaching. Her mother rebuilt the naming shed. Tomas learned letters so no river could take what ink also held. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 7 — High Water",
    text: `A final temptation came as a merchant offering gold for exclusive rights to “name insurance.” Sera refused publicly. “Names aren’t policies,” she said. “They’re relationships. You can’t buy a chorus.” The merchant left. The river, as if amused, sent a warm mist that smelled like bread. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 8 — Spoken Back",
    text: `At year’s end both villages held a Naming Night by the open channel. Every person spoke their full names into water; water answered in soft echoes. Sera spoke Sera Liora Kall and heard all three return without toll. She felt rich in syllables. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 8 — Spoken Back",
    text: `Later she wrote a living ledger—not of thefts, but of restorations—and left it in the naming shed for whoever needed proof that bargains could be repaired. Children drew river-fish in the margins. Ferrin pretended not to cry. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
  {
    chapter: "Chapter 8 — Spoken Back",
    text: `On a quiet morning Sera stood alone at the bank and thanked the Warden without fear. The reed figure inclined. “Keep singing,” it said, and dissolved into ordinary current. Sera walked home through grass still wet with mist that no longer stole. Behind her the river kept its names, and ahead her village kept theirs, and between them the channel ran clear—an unfinished song they had agreed, at last, to finish together each season. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder. Evening settled over familiar tools and made even ordinary iron look briefly sacred. She stayed with the feeling instead of rushing past it, the way a careful smith stays with heat until the metal tells the truth of its readiness. In that patience she found a steadiness stronger than spectacle, and a reminder that courage could look like returning to work after wonder.`,
  },
];
